import './globals.scss';
import styles from './layout.module.scss';
import { Inter } from 'next/font/google';
import TopBar from '@/components/TopBar';
import Nav from './components/Nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.wrapper}>
          <Nav />
          <div className={styles.mainWrapper}>
            <TopBar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
